server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Ruta para el microservicio HOTELES
        - id: hotel-service
          uri: lb://HOTELES
          predicates:
            - Path=/api/habitacion/**
        - id: auth-service
          uri: lb://AUTH
          predicates:
            - Path=/api/usuario/**,/api/login/**
           
        - id: reservas-service
          uri: lb://RESERVAS
          predicates:
            - Path=/api/reservacion/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
