server:
  port: 8092

spring:
  application:
    name: hoteles
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

    

