server:
  port: 8093

spring:
  application:
    name: reservas
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: *
  health:
    circuitbreakers:
      enabled: true 
        
resilience4j:
  circuitbreaker:
    instances:
      usuarioClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - feign.FeignException$NotFound
      habitacionClient:
        registerHealthIndicator: true
        slidingWindowSize: 15
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 60
        ignoreExceptions:
          - com.reservas.shared.exeption.ResourceNotFoundException

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    


